import dotenv from "dotenv";
dotenv.config();
import express from "express";
import cors from "cors";
import { userRouter } from "./routes/user.js";
import { accountRounter } from "./routes/account.js";
import { PORT } from "./config.js";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/v1/user", userRouter);
app.use("/api/v1/account", accountRounter);
app.listen(PORT);
